import type { Metadata } from "next";
import { Geist, Geist_Mono, Federo, Barlow } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App Cake",
  description: "Generated by create next app",
};


const federo = Federo({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-federo",
});

const barlow = Barlow({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-barlow",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${federo.variable} ${barlow.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
